// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: chaos/redisexperimentation/v1/redisexperimentation.proto

package redisexperimentationv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on FaultConfig with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned. When asked to return all errors, validation continues after
// first violation, and the result is a list of violation errors wrapped in
// FaultConfigMultiError, or nil if none found. Otherwise, only the first
// error is returned, if any.
func (m *FaultConfig) Validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetFaultTargeting() == nil {
		err := FaultConfigValidationError{
			field:  "FaultTargeting",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if v, ok := interface{}(m.GetFaultTargeting()).(interface{ Validate(bool) error }); ok {
		if err := v.Validate(all); err != nil {
			err = FaultConfigValidationError{
				field:  "FaultTargeting",
				reason: "embedded message failed validation",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
	}

	switch m.Fault.(type) {

	case *FaultConfig_ErrorFault:

		if v, ok := interface{}(m.GetErrorFault()).(interface{ Validate(bool) error }); ok {
			if err := v.Validate(all); err != nil {
				err = FaultConfigValidationError{
					field:  "ErrorFault",
					reason: "embedded message failed validation",
					cause:  err,
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}
		}

	case *FaultConfig_LatencyFault:

		if v, ok := interface{}(m.GetLatencyFault()).(interface{ Validate(bool) error }); ok {
			if err := v.Validate(all); err != nil {
				err = FaultConfigValidationError{
					field:  "LatencyFault",
					reason: "embedded message failed validation",
					cause:  err,
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}
		}

	default:
		err := FaultConfigValidationError{
			field:  "Fault",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if len(errors) > 0 {
		return FaultConfigMultiError(errors)
	}
	return nil
}

// FaultConfigMultiError is an error wrapping multiple validation errors
// returned by FaultConfig.Validate(true) if the designated constraints aren't met.
type FaultConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FaultConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FaultConfigMultiError) AllErrors() []error { return m }

// FaultConfigValidationError is the validation error returned by
// FaultConfig.Validate if the designated constraints aren't met.
type FaultConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FaultConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FaultConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FaultConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FaultConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FaultConfigValidationError) ErrorName() string { return "FaultConfigValidationError" }

// Error satisfies the builtin error interface
func (e FaultConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFaultConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FaultConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FaultConfigValidationError{}

// Validate checks the field values on ErrorFault with the rules defined in the
// proto definition for this message. If any rules are violated, an error is
// returned. When asked to return all errors, validation continues after first
// violation, and the result is a list of violation errors wrapped in
// ErrorFaultMultiError, or nil if none found. Otherwise, only the first error
// is returned, if any.
func (m *ErrorFault) Validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPercentage() == nil {
		err := ErrorFaultValidationError{
			field:  "Percentage",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if v, ok := interface{}(m.GetPercentage()).(interface{ Validate(bool) error }); ok {
		if err := v.Validate(all); err != nil {
			err = ErrorFaultValidationError{
				field:  "Percentage",
				reason: "embedded message failed validation",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
	}

	if len(errors) > 0 {
		return ErrorFaultMultiError(errors)
	}
	return nil
}

// ErrorFaultMultiError is an error wrapping multiple validation errors
// returned by ErrorFault.Validate(true) if the designated constraints aren't met.
type ErrorFaultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ErrorFaultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ErrorFaultMultiError) AllErrors() []error { return m }

// ErrorFaultValidationError is the validation error returned by
// ErrorFault.Validate if the designated constraints aren't met.
type ErrorFaultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ErrorFaultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ErrorFaultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ErrorFaultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ErrorFaultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ErrorFaultValidationError) ErrorName() string { return "ErrorFaultValidationError" }

// Error satisfies the builtin error interface
func (e ErrorFaultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sErrorFault.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ErrorFaultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ErrorFaultValidationError{}

// Validate checks the field values on LatencyFault with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned. When asked to return all errors, validation continues after
// first violation, and the result is a list of violation errors wrapped in
// LatencyFaultMultiError, or nil if none found. Otherwise, only the first
// error is returned, if any.
func (m *LatencyFault) Validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPercentage() == nil {
		err := LatencyFaultValidationError{
			field:  "Percentage",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if v, ok := interface{}(m.GetPercentage()).(interface{ Validate(bool) error }); ok {
		if err := v.Validate(all); err != nil {
			err = LatencyFaultValidationError{
				field:  "Percentage",
				reason: "embedded message failed validation",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
	}

	if m.GetLatencyDuration() == nil {
		err := LatencyFaultValidationError{
			field:  "LatencyDuration",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if v, ok := interface{}(m.GetLatencyDuration()).(interface{ Validate(bool) error }); ok {
		if err := v.Validate(all); err != nil {
			err = LatencyFaultValidationError{
				field:  "LatencyDuration",
				reason: "embedded message failed validation",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
	}

	if len(errors) > 0 {
		return LatencyFaultMultiError(errors)
	}
	return nil
}

// LatencyFaultMultiError is an error wrapping multiple validation errors
// returned by LatencyFault.Validate(true) if the designated constraints
// aren't met.
type LatencyFaultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LatencyFaultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LatencyFaultMultiError) AllErrors() []error { return m }

// LatencyFaultValidationError is the validation error returned by
// LatencyFault.Validate if the designated constraints aren't met.
type LatencyFaultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LatencyFaultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LatencyFaultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LatencyFaultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LatencyFaultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LatencyFaultValidationError) ErrorName() string { return "LatencyFaultValidationError" }

// Error satisfies the builtin error interface
func (e LatencyFaultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLatencyFault.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LatencyFaultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LatencyFaultValidationError{}

// Validate checks the field values on FaultTargeting with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned. When asked to return all errors, validation continues after
// first violation, and the result is a list of violation errors wrapped in
// FaultTargetingMultiError, or nil if none found. Otherwise, only the first
// error is returned, if any.
func (m *FaultTargeting) Validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if v, ok := interface{}(m.GetUpstreamCluster()).(interface{ Validate(bool) error }); ok {
		if err := v.Validate(all); err != nil {
			err = FaultTargetingValidationError{
				field:  "UpstreamCluster",
				reason: "embedded message failed validation",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
	}

	if v, ok := interface{}(m.GetDownstreamCluster()).(interface{ Validate(bool) error }); ok {
		if err := v.Validate(all); err != nil {
			err = FaultTargetingValidationError{
				field:  "DownstreamCluster",
				reason: "embedded message failed validation",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
	}

	if len(errors) > 0 {
		return FaultTargetingMultiError(errors)
	}
	return nil
}

// FaultTargetingMultiError is an error wrapping multiple validation errors
// returned by FaultTargeting.Validate(true) if the designated constraints
// aren't met.
type FaultTargetingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FaultTargetingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FaultTargetingMultiError) AllErrors() []error { return m }

// FaultTargetingValidationError is the validation error returned by
// FaultTargeting.Validate if the designated constraints aren't met.
type FaultTargetingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FaultTargetingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FaultTargetingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FaultTargetingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FaultTargetingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FaultTargetingValidationError) ErrorName() string { return "FaultTargetingValidationError" }

// Error satisfies the builtin error interface
func (e FaultTargetingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFaultTargeting.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FaultTargetingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FaultTargetingValidationError{}

// Validate checks the field values on SingleCluster with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned. When asked to return all errors, validation continues after
// first violation, and the result is a list of violation errors wrapped in
// SingleClusterMultiError, or nil if none found. Otherwise, only the first
// error is returned, if any.
func (m *SingleCluster) Validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetName()) < 1 {
		err := SingleClusterValidationError{
			field:  "Name",
			reason: "value length must be at least 1 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SingleClusterMultiError(errors)
	}
	return nil
}

// SingleClusterMultiError is an error wrapping multiple validation errors
// returned by SingleCluster.Validate(true) if the designated constraints
// aren't met.
type SingleClusterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SingleClusterMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SingleClusterMultiError) AllErrors() []error { return m }

// SingleClusterValidationError is the validation error returned by
// SingleCluster.Validate if the designated constraints aren't met.
type SingleClusterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SingleClusterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SingleClusterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SingleClusterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SingleClusterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SingleClusterValidationError) ErrorName() string { return "SingleClusterValidationError" }

// Error satisfies the builtin error interface
func (e SingleClusterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSingleCluster.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SingleClusterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SingleClusterValidationError{}

// Validate checks the field values on FaultPercentage with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned. When asked to return all errors, validation continues
// after first violation, and the result is a list of violation errors wrapped
// in FaultPercentageMultiError, or nil if none found. Otherwise, only the
// first error is returned, if any.
func (m *FaultPercentage) Validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetPercentage(); val <= 0 || val > 100 {
		err := FaultPercentageValidationError{
			field:  "Percentage",
			reason: "value must be inside range (0, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return FaultPercentageMultiError(errors)
	}
	return nil
}

// FaultPercentageMultiError is an error wrapping multiple validation errors
// returned by FaultPercentage.Validate(true) if the designated constraints
// aren't met.
type FaultPercentageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FaultPercentageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FaultPercentageMultiError) AllErrors() []error { return m }

// FaultPercentageValidationError is the validation error returned by
// FaultPercentage.Validate if the designated constraints aren't met.
type FaultPercentageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FaultPercentageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FaultPercentageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FaultPercentageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FaultPercentageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FaultPercentageValidationError) ErrorName() string { return "FaultPercentageValidationError" }

// Error satisfies the builtin error interface
func (e FaultPercentageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFaultPercentage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FaultPercentageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FaultPercentageValidationError{}

// Validate checks the field values on FaultLatencyDuration with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned. When asked to return all errors, validation
// continues after first violation, and the result is a list of violation
// errors wrapped in FaultLatencyDurationMultiError, or nil if none found.
// Otherwise, only the first error is returned, if any.
func (m *FaultLatencyDuration) Validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetFixedDurationMs() <= 0 {
		err := FaultLatencyDurationValidationError{
			field:  "FixedDurationMs",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return FaultLatencyDurationMultiError(errors)
	}
	return nil
}

// FaultLatencyDurationMultiError is an error wrapping multiple validation
// errors returned by FaultLatencyDuration.Validate(true) if the designated
// constraints aren't met.
type FaultLatencyDurationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FaultLatencyDurationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FaultLatencyDurationMultiError) AllErrors() []error { return m }

// FaultLatencyDurationValidationError is the validation error returned by
// FaultLatencyDuration.Validate if the designated constraints aren't met.
type FaultLatencyDurationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FaultLatencyDurationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FaultLatencyDurationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FaultLatencyDurationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FaultLatencyDurationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FaultLatencyDurationValidationError) ErrorName() string {
	return "FaultLatencyDurationValidationError"
}

// Error satisfies the builtin error interface
func (e FaultLatencyDurationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFaultLatencyDuration.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FaultLatencyDurationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FaultLatencyDurationValidationError{}
